input_dir: "/data"
# Run dir pattern with {input_dir}.
run_dir_pattern: "20[2-9][0-9]{5}[^/]+"
# Output dir with {input_dir}/{run_dir}/*/*/pod5/
# Can use {run_dir}, {subrun_dir}, and {flowcell} wildcards.
run_output_dir: "/data/{run_dir}/{subrun_dir}/{flowcell}/pod5/basecalling"
# Directory for checkpoints. If contains sha256 hash of {run_dir}_{subrun_dir}_{flowcell}, skips it.
run_chkpt_dir: "complete"

# Dorado settings.
dorado:
  bin: "/opt/logsdon_lab/dorado-1.1.1-linux-x64/bin/dorado"
  model: "sup"
  min_qscore: 10
  modifications: "5mCG_5hmCG"
  modifications_by_run_keyword:
    DMLseq: 5mCG_5hmCG,6mA
  kitname_by_run_keyword:
    RBK114: SQK-RBK114-24
    NBD114: SQK-NBD114-24
  devices: "all"
  correct: false
